version: 2
jobs:
  run-checks:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: node:lts-alpine
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Install  dependencies
          command: npm install
      - run:
          name: Check code with eslint
          command: npm run lint
      - run: 
          name: Run the server
          command: npm run dev
      - run:
          name: Run end-to-end tests
          command:  npm run test:run
workflows:
  version: 2
  stack:
    jobs:
      - run-checks